print ('-------------------------')
print ("The Game Of MASTERMIND \n")
print ('-------------------------')
print ("Rules of the game")
print ("You have to guess the 4 letter color code generated by the computer")
print ("Your guess has to contain unique colors")
print ("For your each guess you will be given clues in order to modify your code for the next attempt ")
print ("Guess the secret color code in as few tries as possible, max number of trials is 10.\n")
print ("Please, enter your color code.\nYou can use red(R), green(G), blue(B), yellow(Y), white(W), pink(P)")
print ('eg: rbgy')
import random
colors = ["R", "G", "B", "Y", "W", "P"]
color_code = random.sample(colors,4)
print(color_code)
attempts = 0
game = True
while game is True:
	t=False
	k=False
	correct_color = ""
	guessed_color = ""
	player_guess = input().upper()
	attempts += 1
	if len(player_guess) != len(color_code):
		print ("\nThe secret code has exactly four colors Try again!")
		print ('Number of attempts left ',(10-attempts))	
		continue	
	for i in range(4):
		if player_guess[i] not in colors:
			k=True
	if k is True:
		print('Please choose from the available colors')
		print ('Number of attempts left ',(10-attempts))	
		continue
	for i in player_guess:
		if player_guess.count(i)>1:
			t=True
	if t is True:
		print('Give an unique code')
		print ('Number of attempts left ',(10-attempts))	
		continue
	if correct_color != "RRRR":
		for i in range(4):
			if player_guess[i] == color_code[i]:
				correct_color += "R"
			if  player_guess[i] != color_code[i] and player_guess[i] in color_code:
				guessed_color += "O"
		print ('The number of letters that are in the correct place',correct_color.count('R'))
		print ('The number of letters that are correct but not in correct position',guessed_color.count('O'))
		print ('Number of attempts left ',(10-attempts))	
	if correct_color == "RRRR":
		if attempts == 1:
			print ('--------------------------------------')
			print ("Wow! You guessed at the first attempt!")
			print ('--------------------------------------')
		else:
			print ('--------------------------------------')
			print ("Great!! You needed " + str(attempts) + " attempts to guess.")
			print ('--------------------------------------')

		game = False		
	if attempts >=1 and attempts <10 and correct_color != "RRRR":
		print ("Next attempt: ")
	elif attempts >= 10:
		print ("You could not decode! The secret color code was: " + str(color_code))	
	while game == False or attempts>=10:
		finish_game = input("\nDo you want to play again (Y/N)?").upper()	
		attempts = 0
		if finish_game =="N":
			print ("Good game!! Byeee!")
			break
		elif finish_game == "Y":
			game = True
			print ("Amazing, let's play it again!! Guess the secret color code: ")